test commit

diff --git a/Jenkinsfile.j2 b/Jenkinsfile.j2
--- a/Jenkinsfile.j2
+++ b/Jenkinsfile.j2
@@ -51,14 +51,14 @@ pipeline {
 
                       echo "'{"buildNumber": "$dpeBuildTag", "tag": "$dpeClFoTag", "buildDate": "$dpeClFoBuildDate" }'"
                       echo "{ \\\"buildNumber\\\": \\\"$dpeBuildTag\\\", \\\"buildDate\\\": \\\"$dpeClFoBuildDate\\\" }" > some-client-text.json
-                      exit 0
+                      exit 1
                   '''
                 }  
               post {
                 failure {
                   script {
-                    //slackSend(color: '#FF0000', message: "FAILURE: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.BUILD_URL} failed stage ${env.FAILURE_STAGE} ")
                     env.FAILURE_STAGE = 'Deploy some client'
+                    slackSend(color: '#FF0000', message: "FAILURE: `${env.JOB_NAME}` #${env.BUILD_NUMBER}:\n${env.BUILD_URL} failed stage ${env.FAILURE_STAGE} ")
                   }
                 }
               }              
